version: '3.9'
services:
    web:
        build: .
        command: flask run --host=0.0.0.0 --port=5000
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=main.py
#        env_file:
#            - .env
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - flask_polls_data:/var/lib/postgresql/data
volumes:
    flask_polls_data:
