version: '3.9'
services:
    web:
        build: .
        command: flask run --host=0.0.0.0 --port=5000
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=main.py
        depends_on:
            - db
    db:
        container_name: postgres_container
        image: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - flask_polls_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    flask_polls_data:
    pgadmin-data:

